variable "vm_count" {}
variable "vm_size" {}
variable "admin_username" {}
variable "admin_public_key" {}
variable "resource_group_name" {}
variable "location" {}
variable "acr_name" {}
variable "subnet_id" {}
variable "CONNECTIONSTRINGS__MONGODB" {}
variable "MONGODB__DATABASENAME" {}
variable "force_recreate" {}
